<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="OrchestrationServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/OrchestrationServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/OrchestrationServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://j2ee.netbeans.org/wsdl/IsmkBpelModule/OrchestrationService">
    <import location="OrchestrationService.wsdl" namespace="http://j2ee.netbeans.org/wsdl/IsmkBpelModule/OrchestrationService"/>
    <plnk:partnerLinkType name="OrchestrationServiceLinkType">
        <plnk:role name="OrchestrationServiceRole" portType="ns:OrchestrationServicePortType"/>
    </plnk:partnerLinkType>
</definitions>

