<?xml version="1.0" encoding="UTF-8"?>
<definitions name="IndicatorResponceService" targetNamespace="http://j2ee.netbeans.org/wsdl/IndicatorResponceService/IndicatorResponceService"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/IndicatorResponceService/IndicatorResponceService" xmlns:ns="http://www.shcherbakov.ru/responce" xmlns:ns0="http://www.shcherbakov.ru/simpleResponce" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/IndicatorResponceService/IndicatorResponceService">
            <xsd:import namespace="http://www.shcherbakov.ru/responce" schemaLocation="responce.xsd"/>
            <xsd:import namespace="http://www.shcherbakov.ru/simpleResponce" schemaLocation="simpleResponce.xsd"/>
        </xsd:schema>
    </types>
    <message name="IndicatorResponceServiceOperationRequest">
        <part name="inputPart" element="ns:responce"/>
    </message>
    <message name="IndicatorResponceServiceOperationResponse">
        <part name="outputPart" element="ns0:simpleResponce"/>
    </message>
    <portType name="IndicatorResponceServicePortType">
        <operation name="IndicatorResponceServiceOperation">
            <input name="input1" message="tns:IndicatorResponceServiceOperationRequest"/>
            <output name="output1" message="tns:IndicatorResponceServiceOperationResponse"/>
        </operation>
    </portType>
    <binding name="IndicatorResponceServicePortTypeBinding" type="tns:IndicatorResponceServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="IndicatorResponceServiceOperation">
            <soap:operation style="document"/>
            <input name="input1">
                <soap:body use="literal" parts="inputPart"/>
            </input>
            <output name="output1">
                <soap:body use="literal" parts="outputPart"/>
            </output>
        </operation>
    </binding>
    <service name="IndicatorResponceServiceService">
        <port name="IndicatorResponceServicePortTypeBindingPort" binding="tns:IndicatorResponceServicePortTypeBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/IndicatorResponceService/IndicatorResponceService/IndicatorResponceServicePortTypeBindingPort"/>
        </port>
    </service>
</definitions>


